[workspace]
authors = ["Oleh Basystyi <basystyo@gmail.com>"]
channels = ["conda-forge"]
name = "colmap"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pycolmap = ">=3.11.1,<4"
pillow = ">=11.1.0,<12"
